version: "3.9"

services:
  db:
    image: postgres:16
    container_name: restaurant_feedback_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurant_feedback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: